# Generated by Django 4.1.6 on 2023-02-10 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpage', '0013_remove_userprofile_phone_num_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Album_description',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='album',
            name='Year_of_release',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='album_format',
            field=models.CharField(choices=[('LP', 'LP'), ('CD', 'CD'), ('MP3', 'MP3'), ('FLAC', 'FLAC')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo_link',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Afro', 'Afro'), ('Blues', 'Blues'), ('Gospel', 'Gospel'), ('Hip hop', 'Hip hop'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Others', 'Others'), ('R & B', 'R & B'), ('Rock', 'Rock'), ('Electronic', 'Electronic'), ('Caribbean', 'Caribbean')], default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('country_of_origin', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile.jpeg', null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpage.artist'),
        ),
    ]
